<form action="<?= BASE_URL . 'modVehiculo/' . $id ?>" method="POST">
<h1>COMPLETE EL CAMPO QUE DESEA ACTUALIZAR</h1> 
<p><?= $id ?>"</p>   
<div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Marca</label>
                <input required name="Marca" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Kilometros</label>
                <input required name="Kilometros" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Patente</label>
                <input required name="Patente" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Modelo</label>
                <input required name="Modelo" type="text" class="form-control">
            </div>
        </div>

    </div>
   
    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>
