<form action="<?= BASE_URL . 'modTask/' . $id ?>" method="POST">
<h1>COMPLETE EL CAMPO QUE DESEA ACTUALIZAR</h1> 
<p><?= $id ?>"</p>   
<div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Marca</label>
                <input required name="Marca" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Origen</label>
                <input required name="Origen" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>FechaFundacion</label>
                <input required name="FechaFundacion" type="text" class="form-control">
            </div>
        </div>

    </div>

   
    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>
