<form action="nuevo-auto" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
        <div class="form-group">
                <label>Marca</label>
                <input required name="marca" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Kilometros</label>
                <input required name="kilometros" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Patente</label>
                <input required name="patente" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Modelo</label>
                <input required name="modelo" type="text" class="form-control">
            </div>
        </div>

    </div>


    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>