<form action="nueva" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Marca</label>
                <input required name="Marca" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Origen</label>
                <input required name="Origen" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>FechaFundacion</label>
                <input required name="FechaFundacion" type="text" class="form-control">
            </div>
        </div>

    </div>

    
    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>