<?php require 'templates/layout/header.phtml' ?>

<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>

<form method='post' action='login'>
    <div class='form-group'>
        <label for='nombre_usuario'>Usuario</label>
        <input type='nombre_usuario' class='form-control' id='nombre_usuario' name='nombre_usuario' required>
    </div>
    <div class='form-group'>
        <label for='contraseña'>Contraseña</label>
        <input type='contraseña' class='form-control' id='contraseña' name='contraseña' required>
    </div>
    <button type='submit' class='btn btn-primary'>Login</button>
</form>

<?php require 'templates/layout/footer.phtml' ?>
