<?php require 'templates/layout/header.phtml' ?>


<?php if(isset($_SESSION['ID_USER'])) {?>
    <?php require 'templates/form_marcas.phtml' ?>
<?php }?> 

<ul class="list-group">
<?php foreach($marcas as $marca): ?>
    <li class="list-group-item item-task <?php if($marca->finalizada): ?> finished <?php endif ?>">
        <div class="label">
            <b><?= htmlspecialchars($marca->Marca) ?></b> | (Origen <?=substr($marca->Origen,0,25)?> <?= $marca->FechaFundacion ?>)
        </div>
        <div class="actions">
                <a href="showVehiculos/<?= $marca->Marca?>" type="button" class='btn btn-success btn-sm ml-auto'>Ver mas</a>
        </div>
        
        <?php if(isset($_SESSION['ID_USER'])) {?>
        <div class="actions">
            <?php if(!$marca->finalizada): ?> 
                <a href="finalizar/<?= $marca->id ?>" type="button" class='btn btn-success btn-sm ml-auto'>Finalizar</a> 
            <?php endif ?>
            <a href="eliminar/<?= $marca->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
            
            <a href="editar/<?= $marca->id ?>" type="button" class='btn btn-alert btn-sm ml-auto'>Editar</a>
        </div>
        <?php }?> 
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> Marcas</small></p>


<?php require 'templates/layout/footer.phtml' ?>
