<?php require 'templates/layout/header.phtml' ?>

<?php if(isset($_SESSION['ID_USER'])) {?>
    <?php require 'templates/form_vehiculos.phtml' ?>
<?php }?> 


<ul class="list-group">
    <li class="list-group-item item-task <?php if($vehiculo->finalizada): ?> finished <?php endif ?>">
        <div class="label">
            <b><?= htmlspecialchars($vehiculo->Marca) ?></b> | <?=($vehiculo->Modelo)?> | Detalles( <?=($vehiculo->Kilometros)?> KM | <?=($vehiculo->Patente)?>)
        </div>
    </li>

</ul>




<?php require 'templates/layout/footer.phtml' ?>